#include <iostream>
#include <format>
#include <fstream>
#include <span>
#include <string>
#include <string_view>
#include <vector>

static std::string format_enum(std::string_view name,
	std::string_view description) 
{
	return std::format(R"(		// {}
		{},
)", description, name);
}

struct Input {
	std::string code;
	std::string description;
};

static void output_header(std::vector<Input>& inputs, const char* input_name,
	const char* replacement, const char* replacement_lowercase) {

	std::cout << std::format(R"(
#pragma once

//NOTE(ches) This file is autogenerated from {1}, please do not modify it

#include <map>

namespace hemera {{

	enum class {0}Code {{
)", replacement, input_name);
	for (const auto& input : inputs) {
		std::cout << format_enum(input.code, input.description);
	}
	std::cout << std::format(R"DONE(
	}};
	struct {0}Info {{
		const char* string_value;
		const char* message;

		{0}Info(const char* string_value, const char* message);
		{0}Info(const {0}Info& other);
		{0}Info({0}Info&& other) noexcept;
		{0}Info& operator=(const {0}Info& other);
		{0}Info& operator=({0}Info&& other) noexcept = delete;
		~{0}Info();
	}};

	extern std::map<{0}Code, {0}Info>* {1}_info_map;
    
    void initialize_{1}_info_map();
    void destroy_{1}_info_map();
}}
)DONE", replacement, replacement_lowercase);

	std::cout << std::endl;
}

static void output_cpp(std::vector<Input>& inputs, const char* input_name, 
	const char* output_name, const char* replacement, 
	const char* replacement_lowercase) {
	
	std::cout << "#include \"" << output_name << ".h\"";
	std::cout << std::format(R"DONE(

//NOTE(ches) This file is autogenerated from {2}, please do not modify it

namespace hemera {{

	{0}Info::{0}Info(const char* string_value, const char* message)
		: string_value{{ string_value }}
		, message{{ message }}
	{{}}
	{0}Info::{0}Info(const {0}Info& other)
		: string_value{{ other.string_value }}
		, message{{ other.message }}
	{{}}
	{0}Info::{0}Info({0}Info&& other) noexcept
		: string_value{{ std::move(other.string_value) }}
		, message{{ std::move(other.message) }}
	{{}}
	{0}Info& {0}Info::operator=(const {0}Info& other) {{
		string_value = other.string_value;
		message = other.message;
		return *this;
	}}
	{0}Info::~{0}Info() = default;

	std::map<{0}Code, {0}Info>* {1}_info_map;

    void initialize_{1}_info_map() {{
       if ({1}_info_map != nullptr) {{
           return;
       }}
       {1}_info_map = new std::map<{0}Code, {0}Info>();
)DONE", replacement, replacement_lowercase, input_name);
	
	for (const auto& input : inputs) {
		std::cout << std::format(
			"       {1}_info_map->insert(std::make_pair({0}Code::{2}, {0}Info{{ \"{2}\", \"{3}\" }}));",
			replacement, replacement_lowercase, input.code, input.description) 
			<< std::endl;
	}

	std::cout << std::format(R"DONE(
    }}
    
    void destroy_{1}_info_map() {{
        if ({1}_info_map != nullptr) {{
            delete {1}_info_map;
            {1}_info_map = nullptr;
        }}
    }}
}}
)DONE", replacement, replacement_lowercase) << std::endl;
}

#define STR_AND_LEN(s) s, sizeof(s)

int main(int argc, char* argv[])
{
	std::span<char*> args(argv, static_cast<size_t>(argc));

	if (args.size() != 4) {
		std::cerr << "Incorrect number of arguments" << std::endl;
		return 1;
	}
	const char* output_name = args[1];
	const char* output_type = args[2];
	const char* input_name = args[3];

	const char* replacement;
	const char* replacement_lowercase;
	if (strncmp(output_name, STR_AND_LEN("hemera_errors")) == 0) {
		replacement = "Error";
		replacement_lowercase = "error";
	}
	else if (strncmp(output_name, STR_AND_LEN("hemera_warnings")) == 0) {
		replacement = "Warning";
		replacement_lowercase = "warning";
	}
	else {
		std::cerr << "Unknown replacement type" << std::endl;
		return 1;
	}

	bool header;
	if (strncmp(output_type, STR_AND_LEN("hpp")) == 0) {
		header = true;
	}
	else if (strncmp(output_type, STR_AND_LEN("cpp")) == 0) {
		header = false;
	}
	else {
		std::cerr << "Unknown file type" << std::endl;
		return 1;
	}

	std::ifstream input_file;
	input_file.open(input_name);

	if (!input_file.is_open()) {
		std::cerr << "Unknown file" << std::endl;
		return 1;
	}

	std::string line;
	std::vector<Input> inputs;

	while (std::getline(input_file, line)) {
		if (line.empty()) {
			continue;
		}
		size_t first_comma = line.find(",");
		if (first_comma == std::string::npos) {
			std::cerr << "Bad file format" << std::endl;
			return 1;
		}
		inputs.emplace_back(line.substr(0, first_comma), line.substr(first_comma + 1));
	}

	if (header) {
		output_header(inputs, input_name, replacement, replacement_lowercase);
	}
	else {
		output_cpp(inputs, input_name, output_name, replacement, replacement_lowercase);
	}

	return 0;
}
